---
- name: copying file
  hosts: all
  become: true
  tasks:
    - name: copying_file
      copy:
        src: /home/admin/index.html
        dest: /home/admin
        mode: 0600

    - name: pkg_install
      yum:
        name: httpd
        state: present

    - name: staring service
      service:
        name: httpd
        state: started

