---
- name: pkg_setup_os_based
  hosts: all
  become: true
  tasks:
    - name: installing httpd
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: pkg_httpd_starting
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: apache2_installation
      yum: 
        name: apache2
        state: presnt
      when: ansible_os_family == "Debian"

    - name: starting_service_apache2
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"
