---
- name: user creation
  become: true
  hosts: all
  tasks:
    - name: list of user creation
      user: name='{{ item }}' state=present
      with_items:
        - raj
        - lakshmi
        - siva
        - harismaran
        - Harismaran
        - Anju
      ignore_errors: yes

