---
# tasks file for setup-apache-role
- name: install httpd
  yum: 
    name: httpd
    state: present
  when: ansible_os_family == "RedHat"
  notify: start httpd service

- name: apache2 install
  apt: 
    name: apache2
    state: present
  when: ansible_os_family == "Debian"
  notify: start apache2 service

- name: copying file
  copy:
    src: /home/admin/index.html
    dest: /var/www/html
    mode: 0666
